import {
  Profile,
  Ministry,
  MinistryMember,
  Role,
  Service,
  Schedule,
  Song,
  Setlist,
  Notification,
  ActivityLog,
  Availability
} from '../types/database';

export const INITIAL_MINISTRY: Ministry = {
  id: 'min-1',
  name: 'Ministério de Louvor IENOV',
  church_name: 'IENOV',
  logo_url: '/ienov-logo.png',
  description: 'Adorando a Deus em espírito e em verdade através da música.',
  created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  updated_at: new Date().toISOString(),
};

export const INITIAL_ROLES: Role[] = [
  { id: 'role-ministracao', ministry_id: 'min-1', name: 'Ministração', category: 'lideranca', active: true, created_at: new Date().toISOString() },
  { id: 'role-vocal', ministry_id: 'min-1', name: 'Vocal', category: 'vocal', active: true, created_at: new Date().toISOString() },
  { id: 'role-violao', ministry_id: 'min-1', name: 'Violão', category: 'harmonia', active: true, created_at: new Date().toISOString() },
  { id: 'role-guitarra', ministry_id: 'min-1', name: 'Guitarra', category: 'harmonia', active: true, created_at: new Date().toISOString() },
  { id: 'role-teclado', ministry_id: 'min-1', name: 'Teclado', category: 'harmonia', active: true, created_at: new Date().toISOString() },
  { id: 'role-baixo', ministry_id: 'min-1', name: 'Baixo', category: 'ritmo', active: true, created_at: new Date().toISOString() },
  { id: 'role-bateria', ministry_id: 'min-1', name: 'Bateria', category: 'ritmo', active: true, created_at: new Date().toISOString() },
  { id: 'role-som', ministry_id: 'min-1', name: 'Sonoplastia', category: 'tecnica', active: true, created_at: new Date().toISOString() },
  { id: 'role-midia', ministry_id: 'min-1', name: 'Multimídia', category: 'tecnica', active: true, created_at: new Date().toISOString() },
];

export const INITIAL_PROFILES: Profile[] = [
  {
    id: 'user-lucas',
    full_name: 'Lucas Gomes',
    username: 'lider.master',
    email: 'lucasgomes3621@gmail.com',
    phone: '(11) 98765-4321',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    active: true,
    must_change_password: false,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'user-joao',
    full_name: 'João Silva',
    username: 'joao.silva',
    email: 'joao.silva@email.com',
    phone: '(11) 98888-1234',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    active: true,
    must_change_password: true, // Requires ALTERAR SENHA on first login as per spec
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'user-davi',
    full_name: 'Davi Oliveira',
    username: 'davi.batera',
    email: 'davi.baterista@email.com',
    phone: '(11) 96543-2109',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    active: true,
    must_change_password: false,
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'user-mariana',
    full_name: 'Mariana Costa',
    username: 'mariana.costa',
    email: 'mariana.costa@email.com',
    phone: '(11) 97654-3210',
    avatar_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
    active: true,
    must_change_password: false,
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'user-beatriz',
    full_name: 'Beatriz Lima',
    username: 'beatriz.piano',
    email: 'beatriz.piano@email.com',
    phone: '(11) 95432-1098',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
    active: true,
    must_change_password: false,
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'user-gabriel',
    full_name: 'Gabriel Santos',
    username: 'gabriel.guitar',
    email: 'gabriel.guitar@email.com',
    phone: '(11) 94321-0987',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    active: true,
    must_change_password: false,
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'user-thiago',
    full_name: 'Thiago Rocha',
    username: 'thiago.som',
    email: 'thiago.som@email.com',
    phone: '(11) 93210-9876',
    avatar_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80',
    active: true,
    must_change_password: false,
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_MEMBERS: MinistryMember[] = [
  {
    id: 'mm-lucas',
    ministry_id: 'min-1',
    user_id: 'user-lucas',
    role: 'MASTER_ADMIN',
    active: true,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    profile: INITIAL_PROFILES[0],
    roles: [INITIAL_ROLES[0], INITIAL_ROLES[1]], // Vocal, Violão
  },
  {
    id: 'mm-joao',
    ministry_id: 'min-1',
    user_id: 'user-joao',
    role: 'MEMBER',
    active: true,
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    profile: INITIAL_PROFILES[1],
    roles: [INITIAL_ROLES[2]], // Guitarra
  },
  {
    id: 'mm-davi',
    ministry_id: 'min-1',
    user_id: 'user-davi',
    role: 'MEMBER',
    active: true,
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    profile: INITIAL_PROFILES[2],
    roles: [INITIAL_ROLES[5]], // Bateria
  },
  {
    id: 'mm-mariana',
    ministry_id: 'min-1',
    user_id: 'user-mariana',
    role: 'MINISTER',
    active: true,
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
    profile: INITIAL_PROFILES[3],
    roles: [INITIAL_ROLES[0]], // Vocal
  },
  {
    id: 'mm-beatriz',
    ministry_id: 'min-1',
    user_id: 'user-beatriz',
    role: 'MEMBER',
    active: true,
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    profile: INITIAL_PROFILES[4],
    roles: [INITIAL_ROLES[3]], // Teclado
  },
  {
    id: 'mm-gabriel',
    ministry_id: 'min-1',
    user_id: 'user-gabriel',
    role: 'MEMBER',
    active: true,
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    profile: INITIAL_PROFILES[5],
    roles: [INITIAL_ROLES[2], INITIAL_ROLES[4]], // Guitarra, Baixo
  },
  {
    id: 'mm-thiago',
    ministry_id: 'min-1',
    user_id: 'user-thiago',
    role: 'MEMBER',
    active: true,
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    profile: INITIAL_PROFILES[6],
    roles: [INITIAL_ROLES[6], INITIAL_ROLES[7]], // Sonoplastia, Multimídia
  },
];

export const INITIAL_SONGS: Song[] = [
  {
    id: 'song-1',
    ministry_id: 'min-1',
    title: 'A Casa É Sua',
    artist: 'Casa Worship',
    original_key: 'G',
    bpm: 70,
    category: 'Adoração',
    notes: 'Iniciar suave no violão e teclado. Entrar bateria no refrão 2.',
    lyrics_reference: 'Essa casa é sua casa, nós deixamos ela pra você, Jesus...',
    active: true,
    created_by: 'user-lucas',
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    links: [
      { id: 'link-1-yt', song_id: 'song-1', platform: 'youtube', url: 'https://www.youtube.com/watch?v=kYJj4l7j9Yw', label: 'Clipe Oficial', created_at: new Date().toISOString() },
      { id: 'link-1-sp', song_id: 'song-1', platform: 'spotify', url: 'https://open.spotify.com/search/A%20Casa%20E%20Sua%20Casa%20Worship', label: 'Spotify', created_at: new Date().toISOString() },
    ],
    last_used_date: new Date(Date.now() - 7 * 86400000).toISOString().split('T')[0],
  },
  {
    id: 'song-2',
    ministry_id: 'min-1',
    title: 'Ousado Amor',
    artist: 'Isaías Saad',
    original_key: 'Bb',
    bpm: 68,
    category: 'Adoração',
    notes: 'Tom original Bb (fazer em G com capotraste na 3ª casa).',
    lyrics_reference: 'Oh, impressionante, infinito e ousado amor de Deus...',
    active: true,
    created_by: 'user-lucas',
    created_at: new Date(Date.now() - 18 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    links: [
      { id: 'link-2-yt', song_id: 'song-2', platform: 'youtube', url: 'https://www.youtube.com/watch?v=s8Y8mJ8f7kY', label: 'Versão Oficial', created_at: new Date().toISOString() },
      { id: 'link-2-sp', song_id: 'song-2', platform: 'spotify', url: 'https://open.spotify.com/search/Ousado%20Amor%20Isaias%20Saad', label: 'Spotify', created_at: new Date().toISOString() },
    ],
  },
  {
    id: 'song-3',
    ministry_id: 'min-1',
    title: 'Bondade de Deus',
    artist: 'Isaías Saad feat. Luma Elpidio',
    original_key: 'G',
    bpm: 71,
    category: 'Adoração',
    notes: 'Dueto nos versos 2 e ponte.',
    lyrics_reference: 'Tua voz me guia pelos vales, na escuridão tua luz reluz...',
    active: true,
    created_by: 'user-mariana',
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    links: [
      { id: 'link-3-yt', song_id: 'song-3', platform: 'youtube', url: 'https://www.youtube.com/watch?v=0eXj3_JmFkI', label: 'Vídeo Oficial', created_at: new Date().toISOString() },
    ],
    last_used_date: new Date().toISOString().split('T')[0],
  },
  {
    id: 'song-4',
    ministry_id: 'min-1',
    title: 'Ruja o Leão',
    artist: 'Talita Catanzaro',
    original_key: 'Em',
    bpm: 128,
    category: 'Celebração',
    notes: 'Dinâmica alta, solo de guitarra na ponte.',
    lyrics_reference: 'Que o Leão de Judá ruja neste lugar...',
    active: true,
    created_by: 'user-lucas',
    created_at: new Date(Date.now() - 12 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    links: [
      { id: 'link-4-yt', song_id: 'song-4', platform: 'youtube', url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', label: 'Versão ao vivo', created_at: new Date().toISOString() },
    ],
  },
  {
    id: 'song-5',
    ministry_id: 'min-1',
    title: 'Lindo És + Só Quero Ver Você',
    artist: 'Livres para Adorar',
    original_key: 'D',
    bpm: 74,
    category: 'Adoração',
    notes: 'Medley contínuo. Momento de ministração espontânea.',
    lyrics_reference: 'Lindo, lindo, lindo és, glória, glória eu te dou...',
    active: true,
    created_by: 'user-mariana',
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    links: [
      { id: 'link-5-yt', song_id: 'song-5', platform: 'youtube', url: 'https://www.youtube.com/watch?v=video5', label: 'Gravação Oficial', created_at: new Date().toISOString() },
    ],
  },
  {
    id: 'song-6',
    ministry_id: 'min-1',
    title: 'Porque Ele Vive',
    artist: 'Versão Contemporânea',
    original_key: 'A',
    bpm: 76,
    category: 'Louvor',
    notes: 'Hino tradicional com arranjo moderno.',
    lyrics_reference: 'Deus enviou seu Filho amado para salvar...',
    active: true,
    created_by: 'user-lucas',
    created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    links: [],
  },
  {
    id: 'song-7',
    ministry_id: 'min-1',
    title: 'Grande É o Senhor',
    artist: 'Adhemar de Campos',
    original_key: 'A',
    bpm: 110,
    category: 'Celebração',
    notes: 'Abertura do culto alegre com palmas.',
    lyrics_reference: 'Grande é o Senhor e mui digno de louvor...',
    active: true,
    created_by: 'user-lucas',
    created_at: new Date(Date.now() - 6 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    links: [],
  },
];

// Helper to format date offset from today
const getOffsetDate = (days: number) => {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString().split('T')[0];
};

export const INITIAL_SERVICES: Service[] = [
  {
    id: 'srv-1',
    ministry_id: 'min-1',
    title: 'Culto da Família — Domingo Noite',
    service_type: 'Culto de Domingo - Noite',
    date: getOffsetDate(2),
    start_time: '18:00',
    end_time: '20:00',
    location: 'Templo Principal',
    notes: 'O ensaio será na quinta-feira às 19:30.',
    status: 'scheduled',
    created_by: 'user-lucas',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'srv-ceia',
    ministry_id: 'min-1',
    title: 'Culto de Santa Ceia — Domingo Manhã',
    service_type: 'Culto de Domingo - Santa Ceia',
    date: getOffsetDate(9),
    start_time: '09:00',
    end_time: '11:30',
    location: 'Templo Principal',
    notes: 'O ensaio será na quinta-feira às 19:30.',
    status: 'scheduled',
    created_by: 'user-lucas',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'srv-2',
    ministry_id: 'min-1',
    title: 'Culto de Quarta-feira',
    service_type: 'Culto de Quarta',
    date: getOffsetDate(5),
    start_time: '19:30',
    end_time: '21:00',
    location: 'Templo Principal',
    notes: '',
    status: 'scheduled',
    created_by: 'user-lucas',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'srv-3',
    ministry_id: 'min-1',
    title: 'Culto de Sexta-feira',
    service_type: 'Culto de Sexta',
    date: getOffsetDate(7),
    start_time: '19:30',
    end_time: '21:00',
    location: 'Templo Principal',
    notes: '',
    status: 'scheduled',
    created_by: 'user-lucas',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'srv-ebd',
    ministry_id: 'min-1',
    title: 'Escola Bíblica Dominical (EBD)',
    service_type: 'EBD - Escola Bíblica',
    date: getOffsetDate(16),
    start_time: '09:00',
    end_time: '11:00',
    location: 'Templo Principal',
    notes: 'Chegada às 08:30 para oração.',
    status: 'scheduled',
    created_by: 'user-lucas',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_SCHEDULES: Schedule[] = [
  {
    id: 'sch-1',
    service_id: 'srv-1',
    ministry_id: 'min-1',
    created_by: 'user-lucas',
    repertoire_responsible_id: 'mm-mariana',
    status: 'published',
    notes: 'O ensaio será na quinta-feira às 19:30',
    published_at: new Date(Date.now() - 86400000).toISOString(),
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    service: INITIAL_SERVICES[0],
    repertoire_responsible: INITIAL_MEMBERS[3],
    members: [
      {
        id: 'sm-1',
        schedule_id: 'sch-1',
        ministry_member_id: 'mm-lucas',
        role_id: 'role-violao',
        confirmation_status: 'confirmed',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        member: INITIAL_MEMBERS[0],
        role: INITIAL_ROLES[2],
      },
      {
        id: 'sm-2',
        schedule_id: 'sch-1',
        ministry_member_id: 'mm-mariana',
        role_id: 'role-ministracao',
        confirmation_status: 'confirmed',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        member: INITIAL_MEMBERS[3],
        role: INITIAL_ROLES[0],
      },
      {
        id: 'sm-3',
        schedule_id: 'sch-1',
        ministry_member_id: 'mm-davi',
        role_id: 'role-bateria',
        confirmation_status: 'pending',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        member: INITIAL_MEMBERS[2],
        role: INITIAL_ROLES[5],
      },
      {
        id: 'sm-4',
        schedule_id: 'sch-1',
        ministry_member_id: 'mm-beatriz',
        role_id: 'role-teclado',
        confirmation_status: 'confirmed',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        member: INITIAL_MEMBERS[3],
        role: INITIAL_ROLES[3],
      },
      {
        id: 'sm-5',
        schedule_id: 'sch-1',
        ministry_member_id: 'mm-thiago',
        role_id: 'role-som',
        confirmation_status: 'pending',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        member: INITIAL_MEMBERS[5],
        role: INITIAL_ROLES[6],
      },
    ],
  },
  {
    id: 'sch-ceia',
    service_id: 'srv-ceia',
    ministry_id: 'min-1',
    created_by: 'user-lucas',
    repertoire_responsible_id: 'mm-lucas',
    status: 'published',
    notes: 'O ensaio será na quinta-feira às 19:30',
    published_at: new Date(Date.now() - 60000000).toISOString(),
    created_at: new Date(Date.now() - 100000000).toISOString(),
    updated_at: new Date().toISOString(),
    service: INITIAL_SERVICES[1],
    repertoire_responsible: INITIAL_MEMBERS[0],
    members: [
      {
        id: 'sm-c1',
        schedule_id: 'sch-ceia',
        ministry_member_id: 'mm-lucas',
        role_id: 'role-ministracao',
        confirmation_status: 'confirmed',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        member: INITIAL_MEMBERS[0],
        role: INITIAL_ROLES[0],
      },
      {
        id: 'sm-c2',
        schedule_id: 'sch-ceia',
        ministry_member_id: 'mm-beatriz',
        role_id: 'role-teclado',
        confirmation_status: 'confirmed',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        member: INITIAL_MEMBERS[3],
        role: INITIAL_ROLES[3],
      },
      {
        id: 'sm-c3',
        schedule_id: 'sch-ceia',
        ministry_member_id: 'mm-thiago',
        role_id: 'role-som',
        confirmation_status: 'confirmed',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        member: INITIAL_MEMBERS[5],
        role: INITIAL_ROLES[6],
      },
    ],
  },
  {
    id: 'sch-2',
    service_id: 'srv-2',
    ministry_id: 'min-1',
    created_by: 'user-lucas',
    repertoire_responsible_id: 'mm-lucas',
    status: 'published',
    notes: '',
    published_at: new Date(Date.now() - 43200000).toISOString(),
    created_at: new Date(Date.now() - 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    service: INITIAL_SERVICES[2],
    repertoire_responsible: INITIAL_MEMBERS[0],
    members: [
      {
        id: 'sm-21',
        schedule_id: 'sch-2',
        ministry_member_id: 'mm-lucas',
        role_id: 'role-violao',
        confirmation_status: 'confirmed',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        member: INITIAL_MEMBERS[0],
        role: INITIAL_ROLES[1],
      },
      {
        id: 'sm-22',
        schedule_id: 'sch-2',
        ministry_member_id: 'mm-gabriel',
        role_id: 'role-baixo',
        confirmation_status: 'pending',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        member: INITIAL_MEMBERS[4],
        role: INITIAL_ROLES[4],
      },
    ],
  },
];

export const INITIAL_SETLISTS: Setlist[] = [
  {
    id: 'set-1',
    ministry_id: 'min-1',
    service_id: 'srv-1',
    responsible_member_id: 'mm-mariana',
    status: 'published',
    published_at: new Date().toISOString(),
    created_at: new Date(Date.now() - 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    service: INITIAL_SERVICES[0],
    responsible_member: INITIAL_MEMBERS[1],
    songs: [
      {
        id: 'ss-1',
        setlist_id: 'set-1',
        song_id: 'song-7',
        position: 1,
        key_override: 'A',
        bpm_override: 110,
        notes: 'Abertura animada com palmas!',
        created_at: new Date().toISOString(),
        song: INITIAL_SONGS[6],
      },
      {
        id: 'ss-2',
        setlist_id: 'set-1',
        song_id: 'song-1',
        position: 2,
        key_override: 'G',
        bpm_override: 70,
        notes: 'Emendar com suavidade na introdução do teclado.',
        created_at: new Date().toISOString(),
        song: INITIAL_SONGS[0],
      },
      {
        id: 'ss-3',
        setlist_id: 'set-1',
        song_id: 'song-3',
        position: 3,
        key_override: 'G',
        bpm_override: 71,
        notes: 'Ponte com oração congregacional.',
        created_at: new Date().toISOString(),
        song: INITIAL_SONGS[2],
      },
      {
        id: 'ss-4',
        setlist_id: 'set-1',
        song_id: 'song-2',
        position: 4,
        key_override: 'G', // overridden from Bb to G
        bpm_override: 68,
        notes: 'Fechamento do momento de louvor.',
        created_at: new Date().toISOString(),
        song: INITIAL_SONGS[1],
      },
    ],
  },
];

export const INITIAL_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-1',
    user_id: 'user-lucas',
    ministry_id: 'min-1',
    type: 'repertoire_published',
    title: '🎵 Repertório Definido!',
    message: 'Mariana Costa publicou o repertório para o Culto de Domingo.',
    related_service_id: 'srv-1',
    related_setlist_id: 'set-1',
    created_at: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'notif-2',
    user_id: 'user-lucas',
    ministry_id: 'min-1',
    type: 'confirmation',
    title: '✅ Escala Confirmada',
    message: 'Beatriz Lima confirmou presença no Culto de Domingo.',
    related_service_id: 'srv-1',
    created_at: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: 'notif-3',
    user_id: 'user-mariana',
    ministry_id: 'min-1',
    type: 'schedule_created',
    title: '📅 Você foi escalada!',
    message: 'Você foi escalada para o Culto de Domingo como Vocal e Responsável pelo Repertório.',
    related_service_id: 'srv-1',
    created_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'notif-4',
    user_id: 'user-davi',
    ministry_id: 'min-1',
    type: 'schedule_created',
    title: '📅 Confirme sua escala',
    message: 'Você foi escalado para Bateria no Culto de Domingo. Por favor, confirme!',
    related_service_id: 'srv-1',
    created_at: new Date(Date.now() - 86400000).toISOString(),
  },
];

export const INITIAL_AVAILABILITY: Availability[] = [
  {
    id: 'av-1',
    ministry_member_id: 'mm-lucas',
    date: getOffsetDate(2),
    status: 'available',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'av-2',
    ministry_member_id: 'mm-mariana',
    date: getOffsetDate(2),
    status: 'available',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'av-3',
    ministry_member_id: 'mm-davi',
    date: getOffsetDate(2),
    status: 'available',
    note: 'Chego às 18h',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'av-4',
    ministry_member_id: 'mm-gabriel',
    date: getOffsetDate(2),
    status: 'unavailable',
    note: 'Viagem de trabalho no fim de semana',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_LOGS: ActivityLog[] = [
  {
    id: 'log-1',
    ministry_id: 'min-1',
    user_id: 'user-mariana',
    user_name: 'Mariana Costa',
    action: 'Publicou o repertório para o Culto de Celebração de Domingo',
    entity_type: 'setlist',
    entity_id: 'set-1',
    created_at: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'log-2',
    ministry_id: 'min-1',
    user_id: 'user-lucas',
    user_name: 'Lucas Gomes',
    action: 'Publicou a escala para o Culto de Domingo',
    entity_type: 'schedule',
    entity_id: 'sch-1',
    created_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'log-3',
    ministry_id: 'min-1',
    user_id: 'user-lucas',
    user_name: 'Lucas Gomes',
    action: 'Cadastrou a música "A Casa É Sua"',
    entity_type: 'song',
    entity_id: 'song-1',
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
  },
];
